// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pantry.Module.Recipe.Database.Contexts;

#nullable disable

namespace Pantry.Module.Recipe.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20250211232856_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pantry.Module.Recipe.Database.Entities.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes", "recipes");
                });

            modelBuilder.Entity("Pantry.Module.Recipe.Database.Entities.RecipeEntity", b =>
                {
                    b.OwnsMany("Pantry.Module.Recipe.Database.Entities.IngredientEntity", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("RecipeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<double>("CountOff")
                                .HasColumnType("double precision");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid?>("PantryItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer");

                            b1.HasKey("RecipeEntityId", "__synthesizedOrdinal");

                            b1.ToTable("Recipes", "recipes");

                            b1.ToJson("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("RecipeEntityId");
                        });

                    b.OwnsOne("Pantry.Module.Recipe.Database.Entities.RecipeDetailsEntity", "Details", b1 =>
                        {
                            b1.Property<Guid>("RecipeEntityId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<DateOnly>>("CookedOn")
                                .IsRequired()
                                .HasColumnType("date[]");

                            b1.PrimitiveCollection<List<int>>("Reviews")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.PrimitiveCollection<List<string>>("Tags")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("RecipeEntityId");

                            b1.ToTable("Recipes", "recipes");

                            b1.ToJson("Details");

                            b1.WithOwner()
                                .HasForeignKey("RecipeEntityId");
                        });

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
