version: '3.4'
networks:
  pantry-recipe-network:
  pantry-plan-network:
  pantry-scanner-network:
  pantry-network:

volumes:
  pantry-recipe-data:
    driver: local
  pantry-plan-data:
    driver: local
  pantry-scanner-data:
    driver: local
  pantry-data:
    driver: local
  rabbitmq-data:
    driver: local

services:
  pantry.recipe.api:
    container_name: pantry-recipe-api
    image: ${DOCKER_REGISTRY-}pantryrecipeapi    
    build:
      context: ../Pantry.Recipe.Api/.
      dockerfile: ../Pantry.Recipe.Api/Dockerfile
    environment:
      - DB_HOST=pantry.recipe.postgres
      - DB_PORT=5432
      - DB_DB=pantry
      - DB_USER=pantry
      - DB_PASSWORD=pantry
    restart: always
    networks:
      - pantry-recipe-network   
      - pantry-network
    depends_on:
      - pantry.recipe.postgres
      - rabbitmq

  pantry.recipe.postgres:
    container_name: pantry-recipe-postgres
    image: postgres:latest
    volumes:
      - pantry-recipe-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=pantry
      - POSTGRES_PASSWORD=pantry
      - POSTGRES_DB=pantry
    networks:
      - pantry-recipe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pantry -d pantry"]
      interval: 5s
      timeout: 5s
      retries: 5

  pantry.plan.api:    
    container_name: pantry-plan-api
    image: ${DOCKER_REGISTRY-}pantryplanapi
    build:
      context: ../Pantry.Plan.Api/.
      dockerfile: ../Pantry.Plan.Api/Dockerfile
    environment:
      - DB_HOST=pantry.plan.postgres
      - DB_PORT=5432
      - DB_DB=pantry
      - DB_USER=pantry
      - DB_PASSWORD=pantry
      - RABBITMQ__HOST=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__USER=pantry
      - RABBITMQ__PASSWORD=pantry
    restart: always
    networks:
      - pantry-plan-network
      - pantry-network
    depends_on:
      - pantry.plan.postgres
      - rabbitmq

  pantry.plan.postgres:
    container_name: pantry-plan-postgres
    image: postgres:latest
    volumes:
      - pantry-plan-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=pantry
      - POSTGRES_PASSWORD=pantry
      - POSTGRES_DB=pantry
    networks:
      - pantry-plan-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pantry -d pantry"]
      interval: 5s
      timeout: 5s
      retries: 5

  pantry.api:    
    container_name: pantry-api
    image: ${DOCKER_REGISTRY-}pantryapi
    build:
      context: ../Pantry.Api/.
      dockerfile: ../Pantry.Api/Dockerfile
    environment:
      - DB_HOST=pantry.postgres
      - DB_PORT=5432
      - DB_DB=pantry
      - DB_USER=pantry
      - DB_PASSWORD=pantry
    restart: always
    networks:
      - pantry-network
    depends_on:
      - pantry.postgres
      - rabbitmq

  pantry.postgres:
    container_name: pantry-postgres
    image: postgres:latest
    volumes:
      - pantry-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    restart: always
    environment:
      - POSTGRES_USER=pantry
      - POSTGRES_PASSWORD=pantry
      - POSTGRES_DB=pantry
    networks:
      - pantry-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pantry -d pantry"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  pantry.scanner.api:    
    container_name: pantry-scanner-api
    image: ${DOCKER_REGISTRY-}pantryscannerapi
    build:
      context: ../Pantry.Scanner.Api/.
      dockerfile: ../Pantry.Scanner.Api/Dockerfile
    environment:
      - DB_HOST=pantry.scanner.postgres
      - DB_PORT=5432
      - DB_DB=pantry
      - DB_USER=pantry
      - DB_PASSWORD=pantry
    restart: always
    networks:
      - pantry-scanner-network
      - pantry-network
    depends_on:
      - pantry.scanner.postgres
      - rabbitmq 

  pantry.scanner.postgres:
    container_name: pantry-scanner-postgres
    image: postgres:latest
    volumes:
      - pantry-scanner-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    restart: always
    environment:
      - POSTGRES_USER=pantry
      - POSTGRES_PASSWORD=pantry
      - POSTGRES_DB=pantry
    networks:
      - pantry-scanner-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pantry -d pantry"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 #http://localhost:15672/#/
    environment:
      - RABBITMQ_DEFAULT_USER=pantry
      - RABBITMQ_DEFAULT_PASS=pantry
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-data:/var/log/rabbitmq
    networks:
      - pantry-network
