name: Build and publish Pantry-API
on:
  push:
    paths:
      - 'SourceCode/PantryBackend/Pantry.Api/**'
      - 'SourceCode/PantryBackend/Pantry.Services/**'
      - 'SourceCode/PantryBackend/Pantry.Shared/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3    
      - 
        name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:          
          github-token: '${{ secrets.PACKAGE_TOKEN }}'
          image-name: pantry-api
          dockerfile: ./SourceCode/PantryBackend/Pantry.Api/Dockerfile
